# Generated by Django 5.0.6 on 2024-06-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=20)),
                ('qualifications', models.CharField(max_length=40)),
                ('age', models.PositiveSmallIntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('next_of_kin', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
            ],
        ),
    ]
