# Generated by Django 5.0.6 on 2024-06-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('attendance', models.PositiveSmallIntegerField()),
                ('class_projects', models.TextField()),
                ('class_activities', models.TextField()),
                ('class_reps', models.TextField()),
                ('assignments', models.TextField()),
                ('class_rules', models.TextField()),
                ('requirements', models.TextField()),
                ('class_members', models.TextField()),
            ],
        ),
    ]
