# Generated by Django 5.0.6 on 2024-06-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('code', models.PositiveSmallIntegerField()),
                ('course_language', models.CharField(max_length=20)),
                ('materials', models.TextField()),
                ('phone_number', models.PositiveBigIntegerField()),
                ('course_fee', models.CharField(max_length=20)),
                ('course_outline', models.TextField()),
            ],
        ),
    ]
